// miniprogram/src/pages/membership/index.vue
<template>
  <view class="container">
    <!-- 当前套餐 -->
    <view v-if="sub" class="card">
      <view class="card-title">当前：{{ sub.planName }}</view>
      <view class="quota-row">
        <view class="quota-item">
          <text class="quota-val">{{ sub.quotas.aiPerMonth === -1 ? '不限' : sub.quotas.aiRemaining }}</text>
          <text class="quota-label">本月AI剩余</text>
        </view>
        <view class="quota-item">
          <text class="quota-val">{{ sub.quotas.maxMembers }}</text>
          <text class="quota-label">成员上限</text>
        </view>
        <view class="quota-item">
          <text class="quota-val">{{ Math.round(sub.quotas.storageLimit / 1073741824) }}</text>
          <text class="quota-label">存储GB</text>
        </view>
      </view>
    </view>

    <!-- 套餐列表 -->
    <view v-for="p in plans" :key="p.plan" class="card plan-card" :class="{ current: p.plan === sub?.plan }">
      <view class="plan-top">
        <text class="plan-name">{{ p.name }}</text>
        <text class="plan-price">￥{{ p.priceYearly }}/年</text>
      </view>
      <view class="plan-features">
        <text v-for="f in p.features" :key="f" class="feature">· {{ f }}</text>
      </view>
      <button
        v-if="p.plan !== sub?.plan && p.plan !== 'FREE'"
        class="btn-primary upgrade-btn"
        :disabled="upgrading === p.plan"
        @tap="onUpgrade(p)"
      >
        {{ upgrading === p.plan ? '处理中...' : '升级' }}
      </button>
      <button v-else-if="p.plan === sub?.plan" class="btn-current" disabled>当前套餐</button>
    </view>

    <text class="dev-tip">开发环境：支付网关未接入，点击升级将模拟支付成功并激活</text>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { memberSubscriptionApi } from '../../utils/api';

const sub = ref<any>(null);
const plans = ref<any[]>([]);
const upgrading = ref<string | null>(null);

const load = async () => {
  const [s, p] = await Promise.all([
    memberSubscriptionApi.subscription().catch(() => null),
    memberSubscriptionApi.plans().catch(() => []),
  ]);
  sub.value = s;
  plans.value = Array.isArray(p) ? p : [];
};

onLoad(load);

const onUpgrade = (plan: any) => {
  uni.showModal({
    title: `升级到${plan.name}`,
    content: `年费￥${plan.priceYearly}，确认升级？`,
    success: async (res) => {
      if (!res.confirm) return;
      upgrading.value = plan.plan;
      try {
        const r = await memberSubscriptionApi.upgrade(plan.plan);
        sub.value = r.subscription || sub.value;
        uni.showToast({ title: '升级成功', icon: 'success' });
      } catch (e) {
        uni.showToast({ title: '升级失败', icon: 'none' });
      } finally {
        upgrading.value = null;
      }
    },
  });
};
</script>

<style scoped>
.quota-row { display: flex; justify-content: space-around; padding: 20rpx 0; }
.quota-item { display: flex; flex-direction: column; align-items: center; }
.quota-val { font-size: 40rpx; font-weight: 700; color: #1677ff; }
.quota-label { font-size: 24rpx; color: #999; margin-top: 8rpx; }
.plan-card { border: 2rpx solid transparent; }
.plan-card.current { border-color: #1677ff; }
.plan-top { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16rpx; }
.plan-name { font-size: 34rpx; font-weight: 600; color: #333; }
.plan-price { font-size: 32rpx; font-weight: 700; color: #1677ff; }
.plan-features { margin-bottom: 20rpx; }
.feature { font-size: 26rpx; color: #666; display: block; margin-bottom: 8rpx; }
.upgrade-btn { margin-top: 10rpx; }
.btn-current { margin-top: 10rpx; background: #f0f0f0; color: #999; border-radius: 12rpx; font-size: 28rpx; }
.dev-tip { font-size: 22rpx; color: #bbb; text-align: center; display: block; margin-top: 20rpx; }
</style>

// web/src/pages/Membership.tsx
import { useEffect, useState } from 'react';
import {
  Card, Row, Col, Progress, Button, Tag, Space, Modal, message, Statistic, Divider, Empty,
} from 'antd';
import { CrownOutlined, CheckOutlined } from '@ant-design/icons';
import api from '../utils/api';

interface Quotas {
  aiPerMonth: number;
  aiUsed: number;
  aiRemaining: number;
  maxMembers: number;
  storageLimit: number;
}
interface Subscription {
  plan: string;
  planName: string;
  status: string;
  endDate: string | null;
  autoRenew: boolean;
  quotas: Quotas;
  features: string[];
}
interface Plan {
  plan: string;
  name: string;
  priceYearly: number;
  aiPerMonth: number;
  maxMembers: number;
  storageLimit: number;
  features: string[];
}

const GB = 1024 * 1024 * 1024;
const fmtGB = (bytes: number) => `${(bytes / GB).toFixed(0)}GB`;
const fmtCount = (n: number) => (n === -1 ? '不限' : `${n}`);

export default function MembershipPage() {
  const [sub, setSub] = useState<Subscription | null>(null);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [upgrading, setUpgrading] = useState<string | null>(null);

  const load = () => {
    setLoading(true);
    Promise.all([
      api.get('/member/subscription'),
      api.get('/member/plans'),
    ])
      .then(([s, p]) => {
        setSub(s.data);
        setPlans(Array.isArray(p.data) ? p.data : []);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  const handleUpgrade = (plan: Plan) => {
    Modal.confirm({
      title: `升级到${plan.name}`,
      content: (
        <div>
          <p>套餐权益：</p>
          <ul style={{ paddingLeft: 20 }}>
            {plan.features.map((f) => <li key={f}>{f}</li>)}
          </ul>
          <p style={{ marginTop: 12 }}>年费：￥{plan.priceYearly}</p>
          <p style={{ color: '#999', fontSize: 12 }}>
            （当前为开发环境，支付网关未接入，确认后将模拟支付成功并直接激活）
          </p>
        </div>
      ),
      okText: '确认升级',
      onOk: async () => {
        setUpgrading(plan.plan);
        try {
          const res = await api.post('/member/upgrade', { plan: plan.plan, paymentMethod: 'WECHAT' });
          message.success(`已成功升级为${plan.name}`);
          setSub(res.data.subscription);
        } finally {
          setUpgrading(null);
        }
      },
    });
  };

  if (loading) return <Card loading />;
  if (!sub) return <Empty description="暂无订阅信息" />;

  const aiPercent = sub.quotas.aiPerMonth === -1 ? 0 : Math.round((sub.quotas.aiUsed / sub.quotas.aiPerMonth) * 100);

  return (
    <div>
      {/* 当前订阅 */}
      <Card
        title={<Space><CrownOutlined style={{ color: '#faad14' }} />当前套餐：{sub.planName}</Space>}
        extra={<Tag color={sub.status === 'ACTIVE' ? 'green' : 'default'}>{sub.status === 'ACTIVE' ? '生效中' : sub.status}</Tag>}
        style={{ marginBottom: 16 }}
      >
        <Row gutter={16}>
          <Col span={6}>
            <Statistic title="本月AI识别" value={sub.quotas.aiUsed} suffix={`/ ${fmtCount(sub.quotas.aiPerMonth)} 次`} />
            {sub.quotas.aiPerMonth !== -1 && (
              <Progress percent={aiPercent} size="small" status={aiPercent >= 100 ? 'exception' : 'normal'} />
            )}
          </Col>
          <Col span={6}>
            <Statistic title="家庭成员上限" value={sub.quotas.maxMembers} suffix="人" />
          </Col>
          <Col span={6}>
            <Statistic title="存储空间" value={fmtGB(sub.quotas.storageLimit)} />
          </Col>
          <Col span={6}>
            <Statistic title="到期时间" value={sub.endDate ? new Date(sub.endDate).toLocaleDateString() : '长期'} />
          </Col>
        </Row>
      </Card>

      <Divider orientation="left">套餐选择</Divider>

      {/* 套餐对比 */}
      <Row gutter={[16, 16]}>
        {plans.map((p) => {
          const isCurrent = p.plan === sub.plan;
          return (
            <Col xs={24} sm={12} lg={6} key={p.plan}>
              <Card
                title={p.name}
                bordered
                style={isCurrent ? { borderColor: '#1677ff', boxShadow: '0 0 8px rgba(22,119,255,0.3)' } : {}}
                actions={[
                  isCurrent ? (
                    <Button type="primary" disabled icon={<CheckOutlined />}>当前套餐</Button>
                  ) : (
                    <Button
                      type={p.plan === 'FREE' ? 'default' : 'primary'}
                      loading={upgrading === p.plan}
                      disabled={p.plan === 'FREE'}
                      onClick={() => handleUpgrade(p)}
                    >
                      {p.plan === 'FREE' ? '免费' : '升级'}
                    </Button>
                  ),
                ]}
              >
                <div style={{ fontSize: 24, fontWeight: 700, color: '#1677ff', marginBottom: 12 }}>
                  ￥{p.priceYearly}<span style={{ fontSize: 13, color: '#999', fontWeight: 400 }}> /年</span>
                </div>
                <ul style={{ paddingLeft: 18, margin: 0, minHeight: 120 }}>
                  {p.features.map((f) => <li key={f} style={{ marginBottom: 6 }}>{f}</li>)}
                </ul>
              </Card>
            </Col>
          );
        })}
      </Row>
    </div>
  );
}
